export const RESEARCHER_INSERT_REQUEST = 'RESEARCHER_INSERT_REQUEST'
export const RESEARCHER_INSERT_SUCESS = 'RESEARCHER_INSERT_SUCESS'
export const RESEARCHER_INSERT_FAIL = 'RESEARCHER_INSERT_FAIL'

export const RESEARCHER_APP_REQUEST = 'RESEARCHER_APP_REQUEST'
export const RESEARCHER_APP_SUCCESS = 'RESEARCHER_APP_SUCCESS'
export const RESEARCHER_APP_FAIL = 'RESEARCHER_APP_FAIL'
export const RESEARCHER_APP_RESET = 'RESEARCHER_APP_RESET'