export const WORKSHOP_LIST_REQUEST_REVIWER = 'WORKSHOP_LIST_REQUEST_REVIWER'
export const WORKSHOP_LIST_SUCCESS_REVIWER = 'WORKSHOP_LIST_SUCCESS_REVIWER'
export const WORKSHOP_LIST_FAIL_REVIWER = 'WORKSHOP_LIST_FAIL_REVIWER'
export const WORKSHOP_LIST_RESET_REVIWER = 'WORKSHOP_LIST_RESET_REVIWER'

export const RESEARCH_LIST_REQUEST_REVIWER = 'RESEARCH_LIST_REQUEST_REVIWER'
export const RESEARCH_LIST_SUCCESS_REVIWER = 'RESEARCH_LIST_SUCCESS_REVIWER'
export const RESEARCH_LIST_FAIL_REVIWER = 'RESEARCH_LIST_FAIL_REVIWER'
export const RESEARCH_LIST_RESET_REVIWER = 'RESEARCH_LIST_RESET_REVIWER'


export const REVIWER_GETWORKSHOP_BYID_REQUEST = 'REVIWER_GETWORKSHOP_BYID_REQUEST'
export const REVIWER_GETWORKSHOP_BYID_SUCCESS = 'REVIWER_GETWORKSHOP_BYID_SUCCESS'
export const REVIWER_GETWORKSHOP_BYID_FAIL = 'REVIWER_GETWORKSHOP_BYID_FAIL'
export const REVIWER_GETWORKSHOP_BYID_RESET = 'REVIWER_GETWORKSHOP_BYID_RESET'

export const REVIWER_APPROVE_WORKSHOP_REQUEST = 'REVIWER_APPROVE_WORKSHOP_REQUEST'
export const REVIWER_APPROVE_WORKSHOP_SUCCESS = 'REVIWER_APPROVE_WORKSHOP_SUCCESS'
export const REVIWER_APPROVE_WORKSHOP_FAIL = 'REVIWER_APPROVE_WORKSHOP_FAIL'
export const REVIWER_APPROVE_WORKSHOP_RESET = 'REVIWER_APPROVE_WORKSHOP_RESET'

export const REVIWER_DECLINE_REQUEST = 'REVIWER_DECLINE_REQUEST'
export const REVIWER_DECLINE_SUCCESS = 'REVIWER_DECLINE_SUCCESS'
export const REVIWER_DECLINE_FAIL = 'REVIWER_DECLINE_FAIL'
export const REVIWER_DECLINE_RESET = 'REVIWER_DECLINE_RESET'


export const REVIWER_RESEARCHER_BYID_REQUEST = 'REVIWER_RESEARCHER_BYID_REQUEST'
export const REVIWER_RESEARCHER_BYID_SUCCESS = 'REVIWER_RESEARCHER_BYID_SUCCESS'
export const REVIWER_RESEARCHER_BYID_FAIL = 'REVIWER_RESEARCHER_BYID_FAIL'
export const REVIWER_RESEARCHER_BYID_RESET = 'REVIWER_RESEARCHER_BYID_RESET'

export const REVIWER_APPROVE_RESERCH_REQUEST = 'REVIWER_APPROVE_RESERCH_REQUEST'
export const REVIWER_APPROVE_RESERCH_SUCCESS = 'REVIWER_APPROVE_RESERCH_SUCCESS'
export const REVIWER_APPROVE_RESERCH_FAIL = 'REVIWER_APPROVE_RESERCH_FAIL'
export const REVIWER_APPROVE_RESERCH_RESET = 'REVIWER_APPROVE_RESERCH_RESET'

export const REVIWER_DECLINE_RESERCH_REQUEST = 'REVIWER_DECLINE_RESERCH_REQUEST'
export const REVIWER_DECLINE_RESERCH_SUCCESS = 'REVIWER_DECLINE_RESERCH_SUCCESS'
export const REVIWER_DECLINE_RESERCH_FAIL = 'REVIWER_DECLINE_RESERCH_FAIL'
export const REVIWER_DECLINE_RESERCH_RESET = 'REVIWER_DECLINE_RESERCH_RESET'