export const WORKSHOP_INSERT_REQUEST = 'WORKSHOP_INSERT_REQUEST'
export const WORKSHOP_INSERT_SUCESS = 'WORKSHOP_INSERT_SUCESS'
export const WORKSHOP_INSERT_FAIL = 'WORKSHOP_INSERT_FAIL'


export const WORKSHOP_APP_REQUEST = 'WORKSHOP_APP_REQUEST'
export const WORKSHOP_APP_SUCCESS = 'WORKSHOP_APP_SUCCESS'
export const WORKSHOP_APP_FAIL = 'WORKSHOP_APP_FAIL'
export const WORKSHOP_APP_RESET = 'WORKSHOP_APP_RESET'